CUDA_VISIBLE_DEVICES=$2 python3 ./lm2am/decode.py \
	--exp-dir $1 \
	--epoch $3 \
	--avg 10 \
	--use-averaged-model True \
	--max-duration 3600 \
	--num-decoder-layers 0 \
	--method ctc-greedy-search \
	--distill True \
	--quant True \
	--lm-name gpt2 \
	--wandb False \
	--lm-tune False \
	--dim-model 256 
